export const dataTypeHotel = [
  { id: 1, name: "Khách sạn căn hộ" },
  { id: 2, name: "Khu nghỉ dưỡng" },
  { id: 3, name: "Nhà nghỉ" },
  { id: 4, name: "Bungalow" },
];
export const data_RoomView = [
  { id: 1, name: "Hướng hồ" },
  { id: 2, name: "Hướng núi" },
  { id: 3, name: "Hướng biển" },
  { id: 4, name: "Hướng vườn" },
  { id: 5, name: "Hướng hồ bơi" },
  { id: 6, name: "Hướng thành phố" },
  { id: 7, name: "Ban công" },
  { id: 8, name: "Hướng một phần" },
  { id: 9, name: "Hướng sân Golf" },
  { id: 10, name: "Hướng công viên" },
  { id: 11, name: "Hướng nội bộ" },
  { id: 12, name: "Gần biển" },
  { id: 13, name: "Hướng sông" },
  { id: 14, name: "Hướng ra địa danh nổi tiếng" },
  { id: 15, name: "Không của sổ" },
  { id: 16, name: "Hướng cảnh quan thiên nhiên" },
];
export const data_amenities_room = [
  {
    id: 1,
    name: "Tiện nghi phòng tắm",
    data: [
      "Bồn tắm jacuzzi",
      "Bình nước nóng",
      "Đồ vệ sinh cá nhân miễn phí",
      "Phòng tắm riêng",
      "Vòi hoa sen",
      "Bồn tắm nằm",
      "Máy sấy tóc",
      "Áo choàng tắm",
      "Khăn tắm",
      "Phòng tắm chung",
    ],
  },
  {
    id: 2,
    name: "Tiện nghi minibar",
    data: [
      "Tủ lạnh",
      "Minibar",
      "Ấm đun nước điện",
      "Trà, cà phê miễn phí",
      "Hoa quả miễn phí",
      "Nước sôi miễn phí",
      "Máy pha cà phê",
    ],
  },
  {
    id: 3,
    name: "Tiện nghi phòng ngủ",
    data: [
      "Tivi",
      "Tivi màn hình phẳng",
      "Đầu đĩa DVD",
      "Tủ",
      "Điều hòa nhiệt độ",
      "Điện thoại",
      "Truyền hình vệ tinh",
      "Két an toàn",
      "Dép đi trong nhà",
      "Lò sưởi",
      "Quạt",
      "Wifi miễn phí",
      "Wifi có tính phí",
      "Bàn trang điểm",
      "Bàn là",
      "Báo cháy",
      "Truyền hình cáp",
      "Máy chống muỗi",
      "Chăn điện",
      "Hệ thống cách âm",
      "Sàn gỗ",
      "Sàn sạch",
    ],
  },
  {
    id: 4,
    name: "Tiện nghi business",
    data: ["Tủ quần áo", "Khu vực tiếp khách", "Ghế sofa", "Bàn làm việc"],
  },
  {
    id: 5,
    name: "Tiện nghi phòng ăn",
    data: ["Bếp và các thiết bị nhà bếp", "Lò vi sóng", "Lò nướng", "Bàn ăn"],
  },
  {
    id: 6,
    name: "Tiện nghi khác",
    data: [
      "Ban công",
      "Chấp nhận thú cưng",
      "Dọn phòng hàng ngày",
      "Dịch vụ báo thức",
      "Kệ để hành lý",
      "Máy giặt",
      "Cửa sổ",
      "Bàn ghế ngoài trời",
      "Giá treo quần áo",
      "Giá phơi quần áo",
      "Máy sấy quần áo",
      "Phòng hút thuốc",
    ],
  },
];
// tour
export const dataTypeTour = [
  { id: 1, name: "Tour du lịch trong nước" },
  { id: 2, name: "Tour du lịch nước ngoài" },
];
export const data_RoomCategory = [
  { id: 1, name: "Phòng Superior Đơn" },
  { id: 2, name: "Phòng Đơn tiêu chuẩn" },
  { id: 3, name: "Phòng Deluxe Đơn" },
  { id: 4, name: "Phòng Đơn" },
  { id: 5, name: "Phòng Đơn Superior" },
];
